export class PacienteNotFound extends Error{}
export class PacienteIdNegative extends Error{}
export class PacienteNegativeNumber extends Error{}
export class PacienteUnnamed extends Error{}
export class PacienteAgeNegative extends Error{}
export class PacienteInvalidDocument extends Error{}
export class PacienteInvalidDate extends Error{}
export class PacienteInvalidGenre extends Error{}
export class PacienteInvalidBloodType extends Error{}
export class PacienteInvalidAddress extends Error{}
